import java.time.YearMonth;

/**
 * Represents a Credit Card with information such as card number, expiry date, CVV, customer details, balance, and credit limit.
 */
public class CreditCard {
    /**
     * The unique identifier for the credit card.
     */
    private int creditCardId;

    /**
     * The customer ID associated with the credit card.
     */
    private int customerId;

    /**
     * The account number associated with the credit card
     */
    private int accountNo;

    /**
     * The current balance on the credit card.
     */
    private double balance;

    /**
     * The credit limit set for the credit card.
     */
    private int creditLimit;

    /**
     * The card number associated with the credit card.
     */
    private String cardNumber;
    /**
     * The Card Verification Value (CVV) of the credit card.
     */
    private int CVV;

    /**
     * The expiry date of the credit card.
     */
    private YearMonth expiryDate;


    /**
     * Constructs a new CreditCard object with the specified Credit Card ID, Customer ID, account number.
     * Balance is set to 0 by default.
     * Credit Limit (per month) is set to 10% of the Customer's annual income
     * Card Number, CVV and Expiry Date are generated by the Credit Card Generator
     *
     * @param creditCardId The credit card ID associated with the credit card.
     * @param customerId   The customer ID associated with the credit card.
     * @param accountNo    The account number associated with the credit card.
     * @param annualIncome The annual income of the Customer applying for the credit card
     */
    public CreditCard(int creditCardId, int customerId, int accountNo, int annualIncome) {
        this.creditCardId = creditCardId;
        this.customerId = customerId;
        this.accountNo = accountNo;
        this.balance = 0.0; // outstanding credit bill balance is 0 for a new credit card
        this.creditLimit = annualIncome / 10; // credit limit per month set to 10% of customer's annual income

        this.cardNumber = CreditCardGenerator.generateCardNumber(accountNo);
        this.CVV = CreditCardGenerator.generateCVV();
        this.expiryDate = CreditCardGenerator.generateExpiryDate();
    }

    /**
     * Construct an existing credit card with the specific Credit Card ID, Customer ID, account number, balance,
     * credit limit, card number, CVV and expiry date.
     *
     * @param creditCardId The credit card ID associated with the credit card.
     * @param customerId   The customer ID associated with the credit card.
     * @param accountNo    The account number associated with the credit card.
     * @param balance      The outstanding balance of the credit bill.
     * @param creditLimit  The credit limit of the credit card.
     * @param cardNumber   The card number associated with the credit card.
     * @param cvv          The Card Verification Value (CVV) associated with the credit card.
     * @param expiryDate   The expiry date of the credit card.
     */
    public CreditCard(int creditCardId, int customerId, int accountNo, double balance, int creditLimit, String cardNumber, int cvv, YearMonth expiryDate) {
        this.creditCardId = creditCardId;
        this.customerId = customerId;
        this.accountNo = accountNo;
        this.balance = balance;
        this.creditLimit = creditLimit;
        this.cardNumber = cardNumber;
        this.CVV = cvv;
        this.expiryDate = expiryDate;
    }

    /**
     * Retrieves the unique credit card ID
     *
     * @return The unique credit card ID
     */
    public int getCreditCardId() {
        return this.creditCardId;
    }

    /**
     * Retrieves the customer ID associated with the credit card
     *
     * @return The customer ID associated with the corresponding credit card
     */
    public int getCustomerId(){
        return this.customerId;
    }

    /**
     * Retrieves the account number associated with the credit card
     *
     * @return The account number associated with the corresponding credit card
     */
    public int getAccountNo(){
        return this.accountNo;
    }

    /**
     * Retrieves the credit card number.
     *
     * @return The credit card number.
     */
    public String getCardNumber() {
        return this.cardNumber;
    }

    /**
     * Retrieves the hashed value of the Card Verification Value (CVV).
     *
     * @return The hashed value of the CVV.
     */
    public String getEncryptedCVV() throws Exception {
        return Security.encryptCVV(String.valueOf(this.CVV));
    }

    /**
     * Retrieves the expiry date of the credit card.
     *
     * @return The expiry date of the credit card.
     */
    public YearMonth getExpiryDate() {
        return this.expiryDate;
    }

    /**
     * Retrieves the current balance on the credit card.
     *
     * @return The balance.
     */
    public double getBalance() {
        return this.balance;
    }

    /**
     * Retrieves the credit limit for the credit card.
     *
     * @return The credit limit of the credit card.
     */
    public int getCreditLimit(){
        return this.creditLimit;
    }

    /**
     * Sets the credit limit for the credit card.
     *
     * @param creditLimit The credit limit to be set.
     */
    public void setCreditLimit(int creditLimit) {
        this.creditLimit = creditLimit;
    }

    /**
     * Attempts to pay the credit card bill with the specified payment amount.
     *
     * @param paymentAmount The amount to be paid.
     * @return True if the payment is successful, False otherwise.
     */
    public boolean payCreditBill(double paymentAmount) {
        // Implementation of payment logic goes here
        return false;
    }

    /**
     * Checks if the credit card is expired.
     *
     * @return True if the credit card is expired, False otherwise.
     */
    public boolean isExpired() {
        // Implementation of expiration check logic goes here
        return false;
    }
}



